# Generated by Django 4.0.4 on 2022-08-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'BigCategories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='big_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.bigcategory'),
        ),
    ]
