# Generated by Django 4.0.4 on 2022-08-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_bigcategory_post_big_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigcategory',
            old_name='name',
            new_name='bigname',
        ),
        migrations.RenameField(
            model_name='bigcategory',
            old_name='slug',
            new_name='bigslug',
        ),
    ]
