# Generated by Django 4.1 on 2022-08-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
