# Generated by Django 4.0.4 on 2022-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
