# Generated by Django 4.0.4 on 2022-08-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_datecategory_post_date_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecategory',
            name='date',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
