# Generated by Django 4.0.4 on 2022-08-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='grade',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='major',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
